# Generated by Django 4.1.3 on 2022-12-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_project_review_tag_remove_teacher_stuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='proj_img',
            field=models.ImageField(blank=True, default='logo_social.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, to='forum.tag'),
        ),
    ]
