# Generated by Django 4.1.3 on 2022-12-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_project_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.TextField(default='hello world', max_length=700),
        ),
    ]
